#!/bin/bash

cd /tmp

OPENSHIFT_GIT_VERSION=$(curl --silent --insecure https://kubernetes.default/version/openshift | jq --raw-output .gitVersion)

echo "OpenShift version $OPENSHIFT_GIT_VERSION"

case "$OPENSHIFT_GIT_VERSION" in
  v1.4*|v3.4*)
    OC_URL=https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz
    ;;
  v1.5*|v3.5*)
    OC_URL=https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz
    ;;
  v3.6*)
    OC_URL=https://github.com/openshift/origin/releases/download/v3.6.1/openshift-origin-client-tools-v3.6.1-008f2d5-linux-64bit.tar.gz
    ;;
  v3.7*)
    OC_URL=https://github.com/openshift/origin/releases/download/v3.7.2/openshift-origin-client-tools-v3.7.2-282e43f-linux-64bit.tar.gz
    ;;
  v3.8*|v3.9*)
    OC_URL=https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
    ;;
  v3.10*)
    OC_URL=https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz
    ;;
  v3.11*)
    OC_URL=https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    ;;
  v3.12*)
    OC_URL=https://mirror.openshift.com/pub/openshift-v3/clients/${OPENSHIFT_GIT_VERSION#v}/linux/oc.tar.gz
    ;;
  *)
    echo "Unknown OpenShift version"
    exit 1
    ;;
esac

echo "Downloading client tools $OC_URL"

curl --location --silent --output oc.tar.gz $OC_URL
tar xfz oc.tar.gz

mkdir /tmp/custom-bin
mv openshift-origin-client-tools*/oc /tmp/custom-bin
export PATH=/tmp/custom-bin:$PATH

exec /usr/local/bin/run-jnlp-client "$@"
