apiVersion: v1
kind: Template
metadata:
  name: ci-fmp-basic-template
parameters:
- name: CI_NAME
  description: "Name of the generated BuildConfig; format: ci-fmp-<runtime>-<mission>"
  required: true
- name: CI_DESCRIPTION
  description: "Description of the mission; format: Runtime | ID: Mission name"
  required: true
- name: CI_GIT_URL
  description: URL of a Git repository containing the tested code
  required: true
- name: CI_GIT_REF
  description: Git ref that should be checked out from CI_GIT_URL
  required: true
  value: master
- name: CI_GITHUB_SECRET
  description: A secret value to use for GitHub webhook URL
  required: true
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: MAVEN_REPO_ADD
  description: URL of an additional Maven repo that should be added to and enabled in ~/.m2/settings.xml
- name: S2I_IMAGE
  description: Name of the S2I image to use; if set, the fabric8.generator.from property will be added to pom.xml
- name: IS_REDHAT
  description: Whether to perform any actions required only for Red Hat builds
  required: true
  value: "false"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "${CI_NAME}"
    annotations:
      ci/description: "${CI_DESCRIPTION}"
      ci/type: "Fabric8 Maven plugin"
  spec:
    completionDeadlineSeconds: 1800
    source:
      type: Git
      git:
        uri: "${CI_GIT_URL}"
        ref: "${CI_GIT_REF}"
    triggers:
    - type: GitHub
      github:
        secret: "${CI_GITHUB_SECRET}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfile: |
          node("rourka-maven") {
            if ('${MAVEN_REPO_ADD}' != '') {
              stage("Adjust settings.xml") {
                sh 'sed -i "s|https://maven.repository.redhat.com/techpreview/all|${MAVEN_REPO_ADD}|" /home/jenkins/.m2/settings.xml'
                sh 'sed -i "s|</activeProfiles>|<activeProfile>jboss-eap-repository</activeProfile></activeProfiles>|" /home/jenkins/.m2/settings.xml'
              }
            }

            stage("Checkout") {
              // can't use just "git url: ..., branch: ..." because that doesn't support tags
              checkout([$class: 'GitSCM',
                        branches: [[name: '${CI_GIT_REF}']],
                        userRemoteConfigs: [[url: '${CI_GIT_URL}']]])

              if ('${IS_REDHAT}' == 'true') {
                if ('${CI_NAME}' == 'ci-fmp-wfswarm-circuit-breaker') {
                  sh "mvn versions:set -DnewVersion=\$(grep '<version>' pom-redhat.xml | sed -n '2 p' | sed -e 's| *</\\?version>||g')"
                }

                sh "mv pom-redhat.xml pom.xml || true"
              }
            }

            try {
              stage("Local test") {
                sh "mvn clean verify -B"
              }

              stage("OpenShift test") {
                if ('${S2I_IMAGE}' != '') {
                  // because Fabric8 Maven plugin prefers <properties> in pom.xml over system properties on Maven cmdline
                  sh "sed -i -e 's|<properties>|<properties><fabric8.generator.from>${S2I_IMAGE}</fabric8.generator.from>|' pom.xml"
                }

                sh "mvn clean verify -B -Popenshift,openshift-it"
              }
            } finally {
              stage("Publish results") {
                junit allowEmptyResults: true, keepLongStdio: true, testResults: "**/target/*-reports/*.xml"
                archiveArtifacts allowEmptyArchive: true, artifacts: "**/target/*-reports/*.xml"
              }
            }
          }
